### ISSUE TITLE
Problem in CMakeLists.txt

### ISSUE THREAD

**Issue by neundorf** [Reference-LAPACK/lapack#125]
Hi,

the top-level CMakeLists.txt contains the following code:

project(LAPACK Fortran)
...
if(USE_OPTIMIZED_LAPACK)
  find_package(LAPACK)
endif()

This find_package(LAPACK) errors out in cmake with the following error:

CMake Error at /usr/share/cmake/Modules/FindThreads.cmake:65 (message):
  FindThreads only works if either C or CXX language is enabled
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBLAS.cmake:474 (find_package)
  /usr/share/cmake/Modules/FindLAPACK.cmake:154 (find_package)
  CMakeLists.txt:244 (find_package)

I.e. FindLAPACK.cmake calls FindThreads.cmake, which errors out if neither C nor CXX have been enabled, and here in this case only the Fortran language has been enabled.
The simple fix for this is to enable also C in the project call:
`
project(LAPACK Fortran C)
`

**Comment by langou** [comment]
Thanks Alex for the bug report and the fix. On the one hand, it would be better to leave `project(LAPACK Fortran)` since LAPACK only requires Fortran. It is kind of awkward to enable C for a build that only requires a Fortran compiler. On the other hand, I do not see any problem with the proposed fix so all good with me. If someone has a comment, please pitch in. Thanks Alex. Cheers, Julien.

**Comment by neundorf** [comment]
It would probably also work to just have 
if(USE_OPTIMIZED_LAPACK)
  enable_language(C)
  find_package(LAPACK)
endif()

I could also have a look at FindLAPACK.cmake, why it requires C or CXX...
