### ISSUE TITLE
xlapy2 not propagating nans

### ISSUE THREAD

**Issue by andreasnoack** [Reference-LAPACK/lapack#147]
(Crossposting from http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=13&t=5136)

E.g.

```fortran
program test_dlapy2
    implicit none

    double precision :: myzero, dlapy2, x, y

    write(*,*) 'write 0.0 and hit enter'
    read(*,*) myzero

    x = 0.0d0/myzero

    write(*,*) 'x is ', x

    y = dlapy2(1.0d0, x)

    write(*,*) 'y is ', y

end program test_dlapy2
```
returns
```fortran
 write 0.0 and hit enter
0.0
 x is                        NaN
 y is    1.4142135623730951
```
This has severe implications because it can cause `xlarfg` to hang during scaling if `alpha=0` and `x` has a nan. I.e. all code that uses elementary reflectors is vulnerable to this as e.g. reported for the SVD in https://github.com/JuliaLang/julia/issues/21757.

It appears that Intel has fixed this in MKL without upstreaming their fix.

**Comment by langou** [comment]
Thanks Andreas, @andreasnoack, and the julia team at large, for the feedback. This is fixed.

For information, LAPY2 was indeed not propagating NaN when X xor Y was a NaN.

For example, if X was a NaN but Y was not, the answer was sqrt(2) * ABS( Y ). Quite a peculiar "feature" . . . 

This was related to FORTRAN INTRINSIC MIN and MAX which, for most compilers, do not propagate NaN. Because of this MIN/MAX feature, old LAPY2 was not propagating NaNs. 

This is fixed now. When X or Y are NaN, then LAPY2 returns a NaN. This is handled explicitly at the start of the routine by checking for NaN.
