### ISSUE TITLE
DOC: Further Details Section for ?SYTRF_RK is missing

### ISSUE THREAD

**Issue by ilayn** [Reference-LAPACK/lapack#164]
I'm currently wrapping ?SYTRF_RK routines in SciPy and, thanks to @langou, I'm removing the _ROOK routines too. 

I'd like to make sure that I'm doing this wrapping with the newer ones properly but unfortunately it seems that the *Further Details* section on NetLib is fallen between the cracks and now it says ` TODO: put correct description`. 

I already have some results so I think I did it properly based on my limited tests but I don't know if there are any edge cases or any other crucial details for that matter.

 Is it possible that these are added to the TODO list (if there is such a list)?

**Comment by langou** [comment]
Hi @scr2016, Can you please have a look? Julien.

**Comment by ilayn** [comment]
Hi again, just a gentle reminder about this 😃

**Comment by ilayn** [comment]
@langou Can we also address this while you are at the documentation rampage? 😃

**Comment by langou** [comment]
Yes, let's continue the rampage ;). 

I am clicking on the link
http://www.netlib.org/lapack//explore-html/d3/db6/group__double_s_ycomputational_ga87dd9faae21db67f106d420ca036f55c.html#ga87dd9faae21db67f106d420ca036f55c and this seems OK to me. Maybe this has been fixed. I do not see a problem. Can you re-explain what the problem is and what you would like to happen?
