### ISSUE TITLE
Finding a faster way to do parallel QR factorization with pivoting (DGEQP3)

### ISSUE THREAD

**Issue by Diazonium** [Reference-LAPACK/lapack#226]
The current implementation of DGEQP3 kinda sucks. For any non-small matrix it spends most of the time in DGEMV, which is extremely memory bandwidth limited when parallelized. The slowness of DGEQP3 is especially an issue for me, because DGELSY spends a large fraction of time doing DGEQP3. (I use DGELSY on MxN matrices where M and N is >3000 and may go up to 10-20 thousand, so parallel performance is really important for me)
AFAIK the current DGEQP3 implementation in OpenBLAS just takes the existing LAPACK code, and uses parallel BLAS where applicable. However this is suboptimal, and large performance improvements may be possible by explicitly parallelizing at the LAPACK level via OpenMP, instead of the BLAS level.
One example for this is the Column Cyclic Distribution method, as described in Algorithm 2, in this paper: http://web.cs.ucdavis.edu/~bai/publications/tomasbaihernandez13.pdf
The authors reported up to 60% performance improvement (!) in DGEQP3, compared to MKL 10.3.
It would be great if such an improved DGEQP3 algorithm could be implemented in OpenBLAS.

**Comment by julielangou** [comment]
[JL 03/08/2018] Forwarding to TN

**Comment by julielangou** [comment]
Hey, here is the answer from our Linear Algebra team at UTK

"A quick look into the paper: the algorithm proposed in that paper is the same as the LAPACK one, the only difference look like is that the authors avoid to open/close the  OpenMP pragma at each call to GEMV which is done inside multithread MKL but rather they open one pragma when the algorithm start and close it at the end.
Since  GEMV consists of the 90% of the time, the other claim does not have sense.
Anyway, the claim that the pragma open/close is expensive might be true in 2013 but is not true today. 
OpenMP did a lot of improvement on the thread pool and I don’t think the open/close of the pragma can be a source of overhead for such matrices size.

So as a result I don’t think that such claim still valid today and thus, the algorithm of this paper (that the user is requesting) might not give the reported speedup.
On the other hand, the authors claim 50-60% speedup so from 10Gflop/s to 15 Gflop/s where the GEMM peak is about 140 Gflop/s but I think this data was obtained without the use of "numactl --interleave all" at least for the MKL run because for their own run they distributes the columns such a way to be 1 column per page. using numactl —interleave all might also change the whole story.

Honestly, my personal view, I don’t see any benefit of implementing the proposed algorithm by openMP because my believe is that it is not going to provide any speedup, today GEMV from MKL is able to reach the peak bandwidth when using numactl interleave all, so my question is: from where the benefit should come.


The comparison with MAGMA also is not mean-full since it look like they have a full GPU implementation while MAGMA is hybrid."

Let us know if you have any question.
Julie
