### ISSUE TITLE
CUNMLQ: LWORK=1 rejected

### ISSUE THREAD

**Issue by amigalemming** [Reference-LAPACK/lapack#260]
SIDE="R", TRANS="C", M=0, N=1.
Workspace query for `CUNMLQ` yields `LWORK=1` and `ZUNMLQ` yields `LWORK=4288`.
The `LWORK=1` is rejected (`INFO=-12`) by `CUNMLQ` when run in normal (computation) mode.

**Comment by martin-frbg** [comment]
Wonder if this is (at least related to) what #443 just fixed

**Comment by martin-frbg** [comment]
Actually probably not related, but from looking at the code I do not see how the reported behaviour can come about with the input as provided - for SIDE="R", LWORK is initially set to M, and later corrected to 1 (due to either of M,N,K being zero). The workspace argument on the other hand is only rejected when it is less than
the MAX of 1 and M - clearly this cannot happen with M=0, LWORK=1. As the code in question does not appear to have changed since two years before the creation of this issue, I can only assume that something
else must have been amiss with either LAPACK or your code. @amigalemming OK to close, or would you like to update this ticket with a reproducer ? 
(I do notice that ZUNMLQ does not report "1" in a workspace query with M,N or K =0, instead it computes a larger number based on various constants, but later returns "1" in the first slot of the work array as its "quick return path" in normal mode. Maybe this is the actual breakage, it certainly looks strange to me ?)
