### ISSUE TITLE
_axpy negative INCX INCY handling?

### ISSUE THREAD

**Issue by brada4** [Reference-LAPACK/lapack#287]
If increments are negative, inputs certainly underflow.
What would be better handling of this - take absolute value or return without action in such cases?

**Comment by langou** [comment]
> If increments are negative, inputs certainly underflow.

Hi @brada4, I do not understand what you mean. If increments are negative, you go backward in your vector. It has been suggested a few times to not allow negative increments. They are not many places where negative increments are used in LAPACK, and this can always be replaced by positive increments. (By changing the pointer at the start instead of at the end.) In any case, Level 1 BLAS standard allows for negative increments. It is what it is. Going back to ``If increments are negative, inputs certainly underflow.`` I do not understand what you mean. If you can clarify, this would be great. Cheers, Julien.

**Comment by brada4** [comment]
I understood.
