### ISSUE TITLE
Unallocated array is passed as a non-optional argument in ./TESTING/LIN/cdrvls.f

### ISSUE THREAD

**Issue by serguei-patchkovskii** [Reference-LAPACK/lapack#426]
Hi,

In both 3.9.0 and the current head branch, ./TESTING/LIN/cdrvls.f calls CGELSY and CGELSS with allocatable RWORK before it has been unallocated. This is undefined behaviour. The relevant code is:

373 *                       Compute workspace needed for CGELSY
374                         CALL CGELSY( M, N, NRHS, A, LDA, B, LDB,
375      $                               IWQ, RCOND, CRANK, WQ, -1, RWORK,
376      $                               INFO )
377                         LWORK_CGELSY = INT( WQ( 1 ) )
378                         LRWORK_CGELSY = 2*N
379 *                       Compute workspace needed for CGELSS
380                         CALL CGELSS( M, N, NRHS, A, LDA, B, LDB, S,
381      $                               RCOND, CRANK, WQ, -1, RWORK, INFO )
382                         LWORK_CGELSS = INT( WQ( 1 ) )
383                         LRWORK_CGELSS = 5*MNMIN

The fix is to replace RWORK in lines 375 and 381 by RWQ

**Comment by martin-frbg** [comment]
Also in this file, line 566 has a call to CSCAL with the scale factor given as a REAL ( `ONE/REAL(NCOLS)` ) instead of a COMPLEX which is not playing nice with any callee that actually tries to read the imaginary part. Using `CONE` here instead of `ONE` should be sufficient.
Unsurprisingly, the exact same problems also appear in TESTING/LIN/zdrvls.f
