### ISSUE TITLE
Add tags for releases

### ISSUE THREAD

**Issue by zerothi** [Reference-LAPACK/lapack#44]
I think it would be nice to have the lapack repo track the releases of lapack, consistently for future easy backtracks.

I have tracked the 3.6.0 and 3.6.1 versions down to:
v3.6.0: 5944165ca899c996310e8f543243e8382c17f88a
v3.6.1: 5efe3599486cc73ceead93f61ce1999eed96be11

To confirm I have downloaded lapack-3.6.0.tgz and lapack-3.6.1.tgz and performed:
```
diff -r git-lapack/ lapack-3.6.X
```
and there where no differences.

I had difficulties from 3.5.0 due to inconsistent history. For instance I get the minimal diff:
using:
5eb720761b5a4543e09b34765b8f2ffc4412cab1
but there is one patch missing (introduced in: 1039d785f63302baa4418a97655d933b6dc030ce)
But there are commits in between, so an exact hash is not available.

I haven't tried any versions prior to 3.5.0.

PS. I have added (annotated) tags on my fork:
https://github.com/zerothi/lapack/releases
but one cannot create PR for equivalent branches (assigning tags does not change history).

I hope you will consider adding the versions.

**Comment by langou** [comment]
Hi Zerothi. Since we were not using git before 3.6.0, it might make sense to not tag in our history before 3.6.0. For 3.5.0, I would go with 89e6d0 or 5eb7207. But I am not sure I want to tag it. Otherwise I think Julie did tag the releases, but indeed I could not see anything. Once I started playing with tagging the releases, I then could see Julie's work. How does 
https://github.com/Reference-LAPACK/lapack/tags and https://github.com/Reference-LAPACK/lapack/releases look now? Can you see the tags and the releases? Let me know if I can close the thread. Happy to work on it some more if needed. Best wishes, Julien.

**Comment by zerothi** [comment]
This looks perfect. Just what I had in mind! :)
