### ISSUE TITLE
Wrong declaration of CDUM in c/zgesdd

### ISSUE THREAD

**Issue by vzecca** [Reference-LAPACK/lapack#467]
In c/zgesdd.f line 276 CDUM(1) is declared.
This is wrong because CDUM(4) is referenced in c/zungbr.f line 234 as A(2,2).

I suggest declaring CDUM(LDA*N) to avoid undefined behaviour.

**Comment by zerothi** [comment]
What about just passing down `A`? The documentation does not specify that `A` isn't referenced if a work-query is asked for.

**Comment by langou** [comment]
Thanks @vzecca. Good catch! I agree with @zerothi that passing A on lines 225 and 234 is correct and should fix the problem. Cheers, Julien.

**Comment by vzecca** [comment]
Julien, the array A in lines 225 and 234 of c/zungbr.f is a formal argument
corresponding to actual argument CDUM in c/zgesdd.
Are you suggesting passing A instead of CDUM in c/zgesdd?
Consider that c/zgesdd alters its formal argument A.

**Comment by martin-frbg** [comment]
As far as I can tell, the whole thing just works because A(2,2) is never actually accessed in a workspace query (this appears to be a bit of "self-documenting" coding in cungbr.f where the query mimicks the actual arguments in the later calculation for the "form Q(2:m,2:m)" case). And CDUM(1) is passed instead of A originally as the calculated workspace size is returned in that first matrix element.
While this code is a bit ugly by today's standards, it should still be legal for legacy code - do you get an actual compiler error here, or only a warning (with the compiler switched to a particularly pedantic mode) ?

**Comment by zerothi** [comment]
> As far as I can tell, the whole thing just works because A(2,2) is never actually accessed in a workspace query (this appears to be a bit of "self-documenting" coding in cungbr.f where the query mimicks the actual arguments in the later calculation for the "form Q(2:m,2:m)" case). And CDUM(1) is passed instead of A originally as the calculated workspace size is returned in that first matrix element.
> While this code is a bit ugly by today's standards, it should still be legal for legacy code - do you get an actual compiler error here, or only a warning (with the compiler switched to a particularly pedantic mode) ?

I agree with this statement. There are no accesses to input matrices in work-size queries. Or at least there shouldn't be!

**Comment by vzecca** [comment]
Yes, the next to last actual argument to CUNGBR is -1 which means this
is just a query
and cdum is not really accessed.

I found this issue with trhe NAG nagfor compiler with option -C, this
is rather strict.

I found another issue, alredy open with number 145.
Any kind soul would look into it and fix it?
It involves accessing the third element of an array with dimension two.
It seems serious to me.

**Comment by martin-frbg** [comment]
That one was already fixed by my #427 in August (probably not realising that there was already an old issue for it), unfortunately the release appears to have been delayed again...
