### ISSUE TITLE
Unused dummy arguments in *LARRV

### ISSUE THREAD

**Issue by zerothi** [Reference-LAPACK/lapack#52]
The `VU` argument in *LARRV is currently not being used to bound the eigenvalue calculation.

Is this omitted on purpose?

Furthermore, there is no check whether `VL < VU` as prescribed in the documentation.

**Comment by langou** [comment]
Thanks Nick

**Comment by zerothi** [comment]
Ok. Thanks for the clarification :)

**Comment by langou** [comment]
Sorry it took me so long to answer. I finally had time to look at the code. 

So `DLARRV` is called by only one subroutine, it is called by`DSTEMR`. In a nutshell, `DSTEMR` first calls `DLARRE` (to get the eigenvalues) then calls DLARRV to get the eigenvectors (if eigenvectors are requested). 

When `RANGE='V'`, `DLARRE` computes the eigenvalues in the interval `(VL,VU]` and computes `M`, how many such eigenvalues there are. This `M` and these`M` eigenvalues are passed on to `DLARRV` which then computes the associated eigenvectors. 

Clearly `VL` and `VU` are needed by `DLARRE` to know the interval where we are looking for eigenvalues.

`VL` and `VU` are needed by `DLARRV` (see subroutine comment) to compute gaps on the left or right end of the extremal eigenvalues in the desired RANGE. 

It turns out that the gap on the right end is not needed so `VU` is not used. 

So yes, we could remove `VU` from the interface. 

I feel it is better to keep `VU` in the interface for many reasons. ((1) Backward compatibility of interfaces, (2) we might need `VU` at some point, (3) we might want to keep `VL` and `VU` together so we might to pass both of them even if only one is used.) So all in all, I feel it is better to keep `VU` in the interface even if it is not used in the subroutine.

I will add a comment to reflect this discussion in the subroutine. 

Thanks for pointing this.

**Comment by zerothi** [comment]
Ok, great! Thanks for the clarification. 
It makes good sense to keep them.

**Comment by langou** [comment]
I have added the following comment in header of DLARRV (ditto for SLARRV)

> Note: `VU` is currently not used by this implmentation of `DLARRV`, `VU` is
passed to `DLARRV` because it could be used compute gaps on the right end
of the extremal eigenvalues. However, with not much initial accuracy in
`LAMBDA` and `VU`, the formula can lead to an overestimation of the right gap
and thus to inadequately early RQI 'convergence'. This is currently
prevented this by forcing a small right gap. And so it turns out that `VU`
is currently not used by this implementation of `DLARRV`.
