### ISSUE TITLE
Version number across all files?

### ISSUE THREAD

**Issue by zerothi** [Reference-LAPACK/lapack#56]
What do the version numbers in each file correspond to? Do they have a meaning or are they meant to be updated at each release?

**Comment by zerothi** [comment]
My inquiry is mainly because, if you need all updated, I would be happy to supply a PR.

**Comment by cconrads-scicomp** [comment]
Similarly, what does \date in each file correspond to? Judging by commits 50d40d78 and ddd12e2c, \date and version number were supposed to be updated for every release. But then again, both commits leave so many files untouched, e.g., SRC/dorcsd2by1.f, dated July 2012.

**Comment by langou** [comment]
We are considering dropping the version number and the dates from the SRC files. 

Does anyone have an opinion on what version number we should have written in the SRC files? 

We mostly have them there for historical reasons. 

Say that we have written `LAPACK 3.6.0` in our DGETRF file. 

We release LAPACK 3.7.0. 

What do we do? 

(1) We update 3.6.0 to 3.7.0 in the file? 

(2) We update 3.6.0 to 3.7.0 in the file only if the file was changed between 3.6.0 and 3.7.0?

(3) We remove this version number in the file and we do not think about it? 

(4) Other suggestions? 

We also have a date, the release date. I assume the release date should follow the version number. So whatever we do for version number, we will do for release date. 

If you have an opinion, please let it known. 

I would be in favor of (3). Happy to hear some opinions.

**Comment by zerothi** [comment]
I think that previous explicit version numbers in the files where for exact determination of its revision. Now, with public repository this need is superseded as the exact commit is exactly tracked. 

Your point number 2) is a valid option, however I find it pointless. It does not give the developers any valuable information, and more than likely committers (maintainers alike) will forget this. I should mention that some codes keep a local revision number in the file which is incremented for each change of the file (autoconf-archive). However, that too seems pointless to me. Any one with basic git knowledge can extract that information (if needed?) in seconds. 

Point 3) seems good, however I think that a second option is more appropriate. From my experience the lapack documentation is often used as it is HTML based and easy to traverse. From my perspective it would be nice to have the released documentation version visible. This removes any concern about the documented version, directly. 
To do this the version numbers should simply be changed to `\version`. One time fix for all files. 

As for the `\date` tags. I too find those pointless. The release date need not be duplicated with the version number, it need only be present in the main page of the documentation. After all, when an error occurs it is the version number which is the reference. What would be nice though, is which release version of lapack the routine was added.?. This would be a good idea in my opinion. 

My 0.02c :)

**Comment by cconrads-scicomp** [comment]
I do not like options 1), 2) because there is a commit changing two lines in up to 3129 Fortran files for every official release.

@zerothi has a point when he says that \date tags are duplicate information. For developers, the date can be determined with git blame and users probably want version numbers. What I do not understand is why the version numbers should be changed to \version; the version is already shown at the very top of the HTML page.

My vote is on 3).

**Comment by victorliu** [comment]
I agree with Christoph that it does not makes sense to update several thousand files each time the version number changes. However, I do also agree with Nick that the HTML documentation should preserved (e.g. www.netlib.org/lapack/explore-3.1.1-html/zgetrf.f.html) since I still find the doxygen to be completely unusable. Of course, the version is in the URL, so perhaps it does not need to be anywhere in the source itself. I liked having version numbers in each file for when I needed to figure out in which versions the file got updated, but with the revision log, I simply need to change my workflow.

So I would be okay with option 3.

**Comment by zerothi** [comment]
@julielangou do you want a PR with removed version numbers? ;)

**Comment by julielangou** [comment]
Dear @zerothi, we actually asked the same question to some vendors who are using LAPACK library, and they did not want them removed ;-)

**Comment by zerothi** [comment]
Ok, no worries then. :) 
So nothing will change.

**Comment by echeresh** [comment]
From Intel side, we like option 3.
