### ISSUE TITLE
accuracy problems with the new LAPACK 3.10  *LARTG implementations

### ISSUE THREAD

**Issue by sergey-v-kuznetsov** [Reference-LAPACK/lapack#629]
**Description**
Under certain conditions the new *LARTG implementations can essentially increase the 2-norm  of initial vector. It can lead to significant loss of accuracy of singular vectors or eigenvectors in ScaLAPACK or LAPACK if the matrix size is large enough. The attached test demonstrates the problem.   The test is for the single complex precision but the precision doesn’t matter. 

In the test  5000 of plane rotations are applied to the vector of  length 2 with the initial 2-norm of 10. If the test is linked with the  reference LAPACK 3.10 built with    
 -bash-4.2$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.    
           
 then the 2-norm of  the resulting vector  is   0.10001301E+02

-bash-4.2$ gfortran test.f liblapack.a librefblas.a 
-bash-4.2$ ./a.out
… 
  The 2-norm of the first vector = 
    0.10001301E+02
…
Max of all errors printed above 
    0.13008118E-02

Everything is excellent with the LAPACK 3.9 clartg and here is the output for the release

-bash-4.2$ ./a.out 
...                                                                                                                                                  
   The 2-norm of the first vector = 
    0.99999943E+01
..
  Error abs(norm of the first column  - initial norm )
    0.57220459E-05
...
  Max of all errors printed above 
    0.57220459E-05

**Checklist**

- [ 
[test.zip](https://github.com/Reference-LAPACK/lapack/files/7325814/test.zip)
] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by langou** [comment]
"Some our old test uses a precomputed singular vectors or precomputed eigenvectors and this kind of tests is considered as passed if and only if || computed eigen/singular vector - precomputed eigen/singular vector || is less than the given threshold."

Do you see the issue only for real arithmetic? Or for complex and real arithmetic?

Since you are mentioned "signs" as opposed to multiplication with "e^(i * theta)" (a complex number of modulus one), I believe you might only be referring to real arithmetic.

For real arithmetic, there is the following convention in 3.9 and in 3.10: "If F exceeds G in magnitude, CS will be positive." So that should give some kind of continuity in between versions. I do not think our test suite check for this though. So it is possible that 3.10 does not respect the convention. I did not look at this. 

Also, we do not know what the convention is "If F does not exceed G in magnitude". Then should we assume that CS is not positive? Or we should assume nothing? I do not know.

You pointed to us in an email that the following lines of code 
          IF( ABS( F ).GT.ABS( G ) .AND. CS.LT.ZERO ) THEN
            CS = -CS
            SN = -SN
            R = -R
         END IF
were in 3.9 and not in 3.10. These lines of code in 3.9 are precisely to make "If F exceeds G in magnitude, CS will be positive." So maybe we could add them back. 

I do not have a good understanding of all this at the moment.




You mentioned in an email

**Comment by sergey-v-kuznetsov** [comment]
Please find below my answers to your questions
> For the 600x600 matrix,

These dimensions (e.g. 600 by 600) are for the DGESDD test and DGESDD is a LAPACK routine. By the way adding the lines IF( ABS( F ).GT.ABS( G ) .AND. CS.LT.ZERO ) THEN CS = -CS SN = -SN R = -R END IF to the LAPACK 3.10 version makes the test pass. I've not investigated yet  why it fails without these lines.
> 
> (*) is the matrix nonsymmetric? On the one hand, I read `pcgehrd`, `pclahqr`, and `pctrevc`, so I am assuming a nonsymmetric matrix. On the other hand, I read "loss of orthogonality" of the right eigenvectors U. I do not understand why U would be orthogonal in the first place. Even if the nonsymmetric matrix were to be normal, we cannot expect a good level of orthogonality between eigenvectors from `pclahqr` when eigenvalues are relatively close.

ScaLAPACK test fails for a 96 by 96 matrix and  yes these ScaLAPACK routines: pcgehrd`, `pclahqr`, and `pctrevc` are for nonsymmetric  eigenvalue problems.  The test collects all eigenvalues and eigenvectors on the master node and  check the accuracy with the help of the LAPACK cget22 routine  http://www.netlib.org/lapack/explore-html/d6/d7c/group__complex__eig_gaba7f4c1d3cb97e0b5812937d39270e81.html  for checking results.  The cget22 is designed by the Netlib team  and since that you should know better how it works.  Just in the case here is  this purpose of the testing routine: 
Purpose:
 The basic test is:

    RESULT(1) = | A E  -  E W | / ( |A| |E| ulp )

 using the 1-norm.  It also tests the normalization of E:

    RESULT(2) = max | m-norm(E(j)) - 1 | / ( n ulp )
                 j

 where E(j) is the j-th eigenvector, and m-norm is the max-norm of a
 vector.  The max-norm of a complex n-vector x in this case is the
 maximum of |re(x(i)| + |im(x(i)| over i = 1, ..., n.

Namely the test fails because RESULT(2) is larger then it is expected. The value of RESULT(1) is ok. In fact the test prints RESULT(1)*eps and RESULT(2)*eps.  I've not checked yet whether  the LAPACK CGEEV  or the same or similar set of LAPACK routines works for this particular matrix since I've got a lot of other work to do. But certainly the test passes if the LAPACK 3.9 clartg is used. 
The matrix is almost real except a few entries and almost all of eigenvalues are complex conjugate pairs.  Moreover the most eigenvalues are known in advance  and mostly they are complex:
     1+ i*2, 1-i*2, 1+i*3, 1-i*3, ..., 1+i*k, 1-i*k, .... The set of plane rotations is computed by the ScaLAPACK routine named clanv2 and they are called for each 2x2 block of the Schur decomposition and the routine also computes complex conjugate pair of eigenvalues.   
 I'll try to prepare a separate case in a couple of weeks if it helps. 
> 
> (*) Can you try the 600x600 matrix with LAPACK and do you see the same issue? It seems that you do not have access to the matrix but only to an object file that you can link to ScaLAPACK MKL. So I assume the answer know. But asking just in case. The algorithms in LAPACK and ScaLAPACK are quite different by now, so I am not sure whether this would help, but I would be curious to know if the matrix breaks LAPACK as well.

See the answer above.  
> 
> (*) "All plane rotations used in my test on your site were taken from the failure. I just dumped a sequence of plane rotations and used them for test generation." Yes, great, perfect, thanks. I am sure this was a lots of work. So thanks. Well, this surely is useful. Thanks.
> 
> (*) As explained but to repeat, we understand that there is a problem 3.10 as shown by the sequence of plane rotations, and that there is no problem with 3.9 for this same sequence. However if we slightly change the sequence then, we see the reverse problem. Namely, 3.10 works and 3.9 does not. It is possible that the sequence of rotations on which 3.9 fails do not occur in practical applications, in which case, 3.9 is a better version for sure. Well, we'll keep digging.

I don't know how to distinguish  practical problem from non-practical one.  It seem you know.  Can you provide a guidance  how to do it?    What should we do if an issue with non-practical problem is filed?

**Comment by langou** [comment]
> I don't know how to distinguish practical problem from non-practical one. It seem you know. Can you provide a guidance how to do it? What should we do if an issue with non-practical problem is filed?

What I meant is the following/

We have two subroutines (1) and (2). 

(A) We have unit test suites that show that (1) and (2) are as buggy. The unit test show that, for 50% of the cases of the unit tests, (1) fails and (2) succeeds. For the other 50% of the cases of the unit tests, (1) succeeds and (2) fails. 

(B) Then we also check (1) and (2) in various test suites, many many test suites, as many as we can. We also give (1) and (2) to users, everyone is testing. And everyone is reporting that their applications with (1) work great and their applications with (2) does not work.

We can describe ``(A) unit test`` as ``non-practical problem``. Maybe ``academic test suite``. And then ``(B) embedding in applications and larger test suites`` as ``practical problems``.

Well this is definitely a gray area. 

> What should we do if an issue with non-practical problem is filed?

Right. That's a good question. 

If an issue with non-practical problem is filed, and we fix the issue so that we are now successful in solving the non-practical problem, but the fix breaks practical problems test suits, we should wait and not release the fix and continue in trying to understand what is going on. 

I think there is an order of practicality. Givens rotations are a mean for our eigensolvers, singular solvers, least squares solvers, applications, etc to work. The first priority is that eigensolvers, singular solvers, least squares solvers, users applications work. The second priority is to have unit tests that exercises the Givens rotations in a wide range so that we can make sure that we understand the few lines of codes and can assess that these lines are correct and behave as expected in the range that we target, and passing these unit tests.

You would hope that there is no disconnect between unit tests and what application needs. That is passing unit test means passing any application. Well, there is a disconnect. Passing unit test does not imply passing practical problem test. Passing practical problem test does not imply passing unit test. Bridging this gap is an important goal.

**Comment by weslleyspereira** [comment]
Hi @sergey-v-kuznetsov. I prepared a PR with a new version of the Givens rotation algorithms. Please, see #631.

The code in #631 gives the following output for the tests you proposed:
```
  The first intial vector 
            (-10.0000000,0.00000000)             (0.00000000,0.00000000)
  Second intial vector 
             (0.00000000,0.00000000)            (-10.0000000,0.00000000)
  Norms of initial vectors    10.0000000    
  Output first vector 
       (-10.0000057,1.606070121E-08) (-4.723551683E-08,-1.907348633E-06)
  Output second vector 
 (-4.723551683E-08,-1.907348633E-06)      (-10.0000057,-1.606070121E-08)
  The 2-norm of the first vector = 
    0.10000006E+02
  Error abs(norm of the first column  - initial norm )
    0.57220459E-05
  The 2-norm of the second vector= 
    0.10000006E+02
  Error abs(norm of the second column - initial norm )
    0.57220459E-05
  Scalar product of the vectors should be around zero.
  Real part of the scalar product 
    0.00000000E+00
  Imaginary part of the scalar product 
    0.00000000E+00
  ABS  of scalar product 
    0.00000000E+00
  Max of all errors printed above 
    0.57220459E-05
```

**Comment by h-vetinari** [comment]
Any update on this? Pity #631 missed 3.10.1 as this might further extend the timeline for MKL conformance (which we depend on to release new lapack versions in conda-forge).

**Comment by weslleyspereira** [comment]
> Any update on this? Pity #631 missed 3.10.1 as this might further extend the timeline for MKL conformance (which we depend on to release new lapack versions in conda-forge).

Hi. There is one update: @langou and I are working on a report about #629 and the changes on #631. We hope to finish it soon. Also, the algorithm for Givens rotations will change with #631. I think a minor release, 3.11.0, is a better place to have new algorithms. I don't think it will take long to have it released.

**Comment by langou** [comment]
3.11 is a minor release. 
I assume 4.0 is a major release.
What is 3.10.1? Ah it is a patch. I see. 
https://semver.org

Good. All good. Just confused.

**Comment by h-vetinari** [comment]
Great to hear, thanks for the update!

**Comment by h-vetinari** [comment]
> > Any update on this? Pity #631 missed 3.10.1 as this might further extend the timeline for MKL conformance (which we depend on to release new lapack versions in conda-forge).
> 
> Hi. There is one update: @langou and I are working on a report about #629 and the changes on #631. We hope to finish it soon. Also, the algorithm for Givens rotations will change with #631. I think a minor release, 3.11.0, is a better place to have new algorithms. I don't think it will take long to have it released.

Any update on this? :)

**Comment by weslleyspereira** [comment]
> Any update on this? :)

Yes! Finally :)
And here is the report: https://arxiv.org/abs/2211.04010.
