### ISSUE TITLE
The matrix size of LAPACKE_sge_trans in lapacke_sgeqrt_work.c seems to be not correct

### ISSUE THREAD

**Issue by sbite0138** [Reference-LAPACK/lapack#766]
**Description**

When LAPACKE_sgeqrt is executed with row major, the following code is executed to convert the result obtained with column major to row major.

https://github.com/Reference-LAPACK/lapack/blob/77fac7e8358b9e350281ea2c4a2b6ea92ad2a602/LAPACKE/src/lapacke_sgeqrt_work.c#L82-L83

Here, `ldt * MIN(m,n)` should be the number of elements in `t_t` (= the number of elements in `t`), but this expression takes more values when ~`ldt > nb`~ `nb > n`.

This causes a segmentation fault when `LAPACKE_sgeqrt` is executed with row major and `ldt > n`.
Here is an example that causes the problem:
```c
#include <stdio.h>
#include <time.h>
#include <lapacke.h>

int main(int argc, char *argv[])
{
    srandom(42);
    const int N = 16;
    const int NB = 4;
    const int LDA = N;
    const int LDT = 100 * N; // set the value so that LDT > N holds.

    // allocate A and T
    float *A = (float *)malloc(N * LDA * sizeof(float));
    float *T = (float *)malloc(N * LDT * sizeof(float));

    // initialize A
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            A[i * LDA + j] = (float)random() / (float)RAND_MAX;
        }
    }

    // call sgeqrt
    LAPACKE_sgeqrt(LAPACK_ROW_MAJOR, N, N, NB, A, LDA, T, LDT);

    // print results
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            printf("% 8f ", A[i * LDA + j]);
        }
        printf("\n");
    }
    printf("\n");
    for (int i = 0; i < NB; i++)
    {
        for (int j = 0; j < N; j++)
        {
            printf("% 8f ", T[i * LDT + j]);
        }
        printf("\n");
    }

    // free memory
    free(A);
    free(T);
    return 0;
}
```

Shouldn't this line look like this?
```c
LAPACKE_sge_trans(LAPACK_COL_MAJOR, nb, MIN(m,n), t_t, ldt_t, t, ldt );
```

I'm thinking that other `LAPACKE_*geqrt` functions may contain similar problems.

**Checklist**

- [x] I've included a minimal example to reproduce the issue
- [x] I'd be willing to make a PR to solve this issue

**Comment by langou** [comment]
Thanks. I agree this is an issue, and your proposed change would fix it. Can you please submit a pull request for LAPACKE_sgeqrt? And also LAPACKE_cgeqrt, LAPACKE_dgeqrt, and LAPACKE_zgeqrt?

**Comment by langou** [comment]
I want to follow up on this issue, the proposed fix corrects the segmentation fault and this is a good thing. 

However there is something that I do not like in the over LAPACKE routines. 

So (*) the user works in row major, (*) they give an array T for the T matrix, (*) column major LAPACK works in the lower parts of T, (*) in order to return in row major, we transpose the array T.

However, we could ask ourselves whether it is OK for LAPACK to writes in the strictly lower parts of T. As of now, I am reading the headers of DGEQRT and there is no promise to leave the strictly lower parts of T unchanged. So what LAPACKE does not break the headers. But we can wonder whether we want to make the header more strict and guarantee that LAPACK will not writes in the strictly lower parts of T. 

All in all, I think maybe, in LAPACKE, we should (step 1) transpose T before calling Column Major LAPACK, (step 2) call Column Major LAPACK, and (step 3) transpose T after.

This is the same as what is done to the array A. 

My preference would be do add a
```c
LAPACKE_sge_trans(LAPACK_COL_MAJOR, nb, MIN(m,n), t_t, ldt_t, t, ldt );
```
before calling 
```c
LAPACK_dgeqrt( &m, &n, &nb, a_t, &lda_t, t_t, &ldt_t, work, &info );
```
(And one after too as proposed by @sbite0138.)

**Comment by langou** [comment]
Hi @sbite0138 

I think we want to leave the line 
``[code=c]
lapack_int ldt_t = MAX(1,ldt); 
```

@scr2016: can you pitch in?

Julien.

**Comment by langou** [comment]
> If you don't mind, may I ask the reason why the change should not be made?

If T has a leading dimension, (meaning `ldt` is strictly larger than `nb`) and you write 
```[code=C]
lapack_int ldt_t = MAX(1,nb);```
then the code will write in some part of the `ldt*n` array `T` that you do not want it to write. It will work on the `nb*n` first entries of `T`. (It's more complicated than that because we have a sequence of upper nb-by-nb triangle, but that's the idea.) What you want it to do is to work on `[0 to nb-1]`, then `[ldt to ldt+nb-1]`, then `[2*ldt to 2*ldt+nb-1]`,  etc. That's the same `nb*n` entries. But not in the same positions in `ldt*n` array `T`.

This is only when `ldt>nb`.

Julien.
