### ISSUE TITLE
Missing text in ssyevx

### ISSUE THREAD

**Issue by HelixPiano** [Reference-LAPACK/lapack#778]
Hello,
maybe there is something I simply don't understand, but it looks like there is some text missing in the explanation of [ssyevx](https://netlib.org/lapack/explore-html/d3/d88/group__real_s_yeigen_ga7f8f413f03a84dbe4ac7a973024d0a48.html).
For variable "A" it says: 
>[...] On entry, the symmetric matrix A. [...]

It is clear that a part of the sentence is missing. Furthermore, I can tell that the function does some modification to the variable, but the text doesn't mention it and also not what exactly happens.

**Comment by martin-frbg** [comment]
Where do you (not) see this ? Could it be that you are looking at the sources of some older release - in 3.11 at least (and the online copy you linked to), the text goes on, detailing what A is in respect to values of UPLO and eventually describing what is returned in A when the subroutine finishes.

**Comment by langou** [comment]
Hi @HelixPiano, 

I like the comments as they currently are and I am not in favor of changing them. I am happy to be downvoted though. So, if more persons express a similar opinion as yours, then we can certainly change the "grammar". Comments below.

Julien.

A "this is" is missing but is implied. The fact the a "this is" is missing does not bother me, and I actually prefer it without the "this is". 

The meaning of
> On entry, the symmetric matrix A. 
is something like
> On entry, the array A represents / contains the symmetric matrix A.

The "On entry" is important in the "sentence" because the array A is ``in/out`` and so it is changed on exit.

The variable is flag is "in/out", this means that the array A is (may be) change in exit.

As far as what the array contains on exit, you write "Furthermore, I can tell that the function does some modification to the variable, but the text doesn't mention it and also not what exactly happens." but it is written: 
> On exit, the lower triangle (if UPLO='L') or the upper triangle (if UPLO='U') of A, including the diagonal, is destroyed.

"It is clear that a part of the sentence is missing." This is a correct statement. The "This is" is missing. The sentence has no verb and no subject. I think this is called a "textual ellipsis".

Julien.

**Comment by HelixPiano** [comment]
Thank you to both of you for the answers.
I should point out that I am new to LAPACK and therefore am not familiar with the way many things work and the terminology.

I think the problem for me is that I don't know what is meant with "destroyed". I thought that it would simply insert zeros to "destroy" (which it apparently doesn't).
So my thought was that the sentence "On entry, the symmetric matrix A." was supposed to be longer and give some more details on what is going on. It didn't occur to me that the text that was following gave the explanation on everything that is happening.

Just for the sake of completion: What does "destroy" mean in this context?

**Comment by langou** [comment]
destroy = contains garbage data
destroy = is used as workspace during the computation and contains no meaningful information
etc.
