### ISSUE TITLE
Routine naming conventions: rook codes

### ISSUE THREAD

**Issue by zerothi** [Reference-LAPACK/lapack#91]
The newly added rook3 codes which is based on BLAS-level 3 are named `*_rk` while the older rook routines are named `*_rook`.

As I suggested in #82, I think they should be named more similarly (here is a suggestion which may not at all reflect their intend and actual code):
1) rename _rook to _rook2, and rename _rk to rook3?
2) rename _rook to _rookkb2, and rename _rk to rookkb3? (rook-Bunch-Kaufman)
3) rename _rook to _rkkb2, and rename _rk to rkkb3? (rook-Bunch-Kaufman)
4) rename _rk to rook3

**Comment by julielangou** [comment]
We started the discussion with the team... Your request makes a lot of sense, yet the team did not make a decision yet. We will keep you posted.

**Comment by zerothi** [comment]
Great, thanks. 
I think it is vital that there will be some kind of guideline for new algorithms. I have also noticed your Aasen routine changes, perhaps some-kind of generic template for generating the routine names will be welcoming for the future. In any case I wait in anticipation ;)

**Comment by langou** [comment]
Hi Nick. Sorry for not coming back to you. We did discuss this (thanks to your input), a recommendation was made and I never came back to you to report. First of, you need to know that the plan is to ultimately get rid of _rook. We might move _rook in DEPRECATED for now, but the goal is to remove _rook from LAPACK. Yet, since the interfaces of _rook and _rk are different, we did not want to use the _rook name for _rk.  So we decided to go with _rk for _rook. (Well,  _rk and _rook seemed equally good so this last point tipped the balance if I recall correctly.) We went for _aa for Aasen. Instead of a possible _aasen. Happy to discuss this some more but the current status is (1) _aa for Aasen, (2) _rk for new rook, and (3) deprecate _rook. I hope this makes sense. How do you feel about this? Thanks for the input in any case, Cheers, Julien.

**Comment by zerothi** [comment]
No worries!
Whatever you decide is fine by me :)
Your proposed scheme makes it consistent which is what I am concerned about ;)

PS. I will let this be open so that you may close it in a PR/commit.

**Comment by langou** [comment]
Hi Nick, I am going to close this thread. I think we are all good with the code as is. Thanks for the input. Cheers, Julien.

**Comment by zerothi** [comment]
Ok, thanks for taking it into consideration!
